"""Freeze the strings that a check reads, or that must not drift, into lit.py.

By extraction — not retyping. Retyping the §18 Negative 31 times is 31 chances to break L10
silently, and the identity block is the whole of the lock for 29 shots (裁定② has no image).
"""
import re
import yaml
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]

# ⛔ **`ROOT` がリポジトリの根を指しているかを、読む前に確かめる。**
#    ⚠️ **2026-09-29**: `parents[3]` を `parents[2]` と誤ると `ROOT` は `<repo>/projects` を指し、
#    この道具は**別の木を読んで、それらしい数を出す**——`verify.py` は「31 specs」と言った。
#    ⚠️ **黙って別の木を読むより、落ちるほうがよい。**
assert (ROOT / "CLAUDE.md").is_file() and (ROOT / "projects" / "odyssey").is_dir(), (
    "ROOT がリポジトリの根を指していない: %s" % ROOT)
SPECS = ROOT / "projects/odyssey/specs/video"
S = {n: (SPECS / ("odyssey-%s.md" % n)).read_text(encoding="utf-8") for n in ("s01", "s03", "s05")}


def sect(t, num, title):
    m = re.search(r"^# %d\. %s\s*\n(.*?)(?=\n# |\Z)" % (num, re.escape(title)), t, re.S | re.M)
    assert m, (num, title)
    return m.group(1)


def slot(t, name):
    m = re.search(r"^## %s\s*\n(.*?)(?=\n## |\n---\s*\n# |\Z)" % re.escape(name), t, re.S | re.M)
    assert m, name
    return m.group(1).strip("\n")


def agree(fn, label):
    vs = {fn(t) for t in S.values()}
    assert len(vs) == 1, "NOT IDENTICAL: %s -> %d variants %r" % (label, len(vs), [v[:80] for v in vs])
    return vs.pop()


out = {}
# L26 reads these four against bible.constants.video. (Duration is per-shot — L23.)
out["CONST"] = agree(lambda t: "\n".join(
    l for l in sect(t, 1, "VIDEO").splitlines()
    if re.match(r"^- (Aspect|Resolution|Frame Rate|Orientation):", l)), "§1 constants")
# L10 requires this block to be identical at the four `negative: covered` change points;
# L21 counts its clauses; L14 reads it. It sits in all 34 specs byte-for-byte.
out["NEGATIVE"] = agree(lambda t: slot(t, "Negative Prompt"), "§18 Negative Prompt")
# The card's Motion character, without the "(Source: …)" attribution — the template writes that.
out["STYLE_MOTION"] = agree(
    lambda t: re.sub(r"\n\(Source:.*$", "", slot(t, "Style Motion"), flags=re.S).strip("\n"),
    "§18 Style Motion")
# §18's preamble: five shared paragraphs, then one the shot writes for itself.
def preamble(t):
    return re.search(r"^# 18\. SEEDANCE 2\.5 PROMPT MAPPING\s*\n(.*?)(?=\n## Master Prompt)",
                     t, re.S | re.M).group(1).strip("\n")
# s01 predates the shape and is hard-wrapped, so it is a variant of its own; s03 and s05 agree.
# The canonical is s03/s05's long-line form, and s01 is normalized to it separately.
out["PREAMBLE_HEAD"] = "\n".join(preamble(S["s05"]).splitlines()[:4])
assert out["PREAMBLE_HEAD"] == "\n".join(preamble(S["s03"]).splitlines()[:4]), "s03 disagrees with s05"
# The identity block: 裁定② attaches no image, so this text is the whole of the lock.
led = yaml.safe_load((ROOT / "projects/odyssey/ledger.yaml").read_text(encoding="utf-8"))
out["IDENTITY"] = led["characters"]["男"]["identity"].strip()
out["IDENTITY_NEG"] = "\n".join("- " + n for n in led["characters"]["男"]["negatives"])

out["FORMAT_NEG"], out["FORMAT_ENV"] = {}, {}
for p in sorted((ROOT / "references/formats").glob("*.md")):
    t = p.read_text(encoding="utf-8")
    m = re.search(r"^## Negative\s*\n+(.+?)(?=\n## |\Z)", t, re.S | re.M)
    assert m, p.stem
    out["FORMAT_NEG"][p.stem] = " ".join(m.group(1).split())
    m2 = re.search(r"^## Environment variables\s*\n+(.+?)(?=\n## |\Z)", t, re.S | re.M)
    out["FORMAT_ENV"][p.stem] = " ".join(m2.group(1).split()) if m2 else ""

# ⚠️ **書き先は `__file__` から取る。** 相対で `open("lit.py", "w")` と書くと、
#    別の場所から走らせた者が**そこに `lit.py` を作り**、`tpl.py` は古いほうを読み続ける。
with open(Path(__file__).resolve().parent / "lit.py", "w", encoding="utf-8") as f:
    f.write("# GENERATED by freeze.py — do not edit by hand.\n")
    f.write("# Extracted from the written specs, the ledger and the format cards, so that the\n")
    f.write("# strings a check reads cannot drift as the remaining specs are written.\n\n")
    for k in ("CONST", "NEGATIVE", "STYLE_MOTION", "PREAMBLE_HEAD", "IDENTITY", "IDENTITY_NEG"):
        f.write("%s = %r\n\n" % (k, out[k]))
    f.write("FORMAT_NEG = %r\n\n" % (out["FORMAT_NEG"],))
    f.write("FORMAT_ENV = %r\n\n" % (out["FORMAT_ENV"],))

print("wrote lit.py")
for k in ("CONST", "NEGATIVE", "STYLE_MOTION", "PREAMBLE_HEAD", "IDENTITY", "IDENTITY_NEG"):
    print("  %-14s %5d chars %3d lines" % (k, len(out[k]), out[k].count("\n") + 1))
print("  %-14s %5d chars (%d sentences)" % ("IDENTITY/sent",
      len(out["IDENTITY"]), len([x for x in re.split(r"(?<=\.)\s+", out["IDENTITY"]) if x.strip()])))
print("  %-14s %3d cards" % ("FORMAT_NEG", len(out["FORMAT_NEG"])))
print("  NEGATIVE clauses: %d" % len([c for c in out["NEGATIVE"].split(",") if c.strip()]))
